#! /usr/bin/env sh

# Autostart programs

[ pgrep -x polybar && killall polybar ] || $HOME/.config/polybar/launch.sh
pgrep -x 'sxhkd' || sxhkd &
pgrep -x 'picom --experimental-backends -b' || picom --experimental-backends -b
pgrep -x 'nm-applet' || nm-applet &
pgrep -x 'volumeicon' || volumeicon &
pgrep -x 'dunst' || dunst &
pgrep -x 'clipmenud' || clipmenud &
xwallpaper --zoom ~/Documents/Pictures/wallpaper.jpg &
pgrep -fl 'pidswallow -gl' || pidswallow -gl
