#! /bin/sh

# When refreshing bspwm, this will remove all previous rules (bad stuff will happen if not)
bspc rule -r "*"

# Set monitor and workspaces (must do this for every monitor)
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

# Autostart programs
picom -b &
killall "nm-applet" # if config is reloaded, kill programs that can have more than one instance
nm-applet &
killall "volumeicon"
volumeicon &
feh --bg-fill --no-fehbg ~/Documents/img.jpg &

# Start polybar
$HOME/.config/polybar/launch.sh

# General configuration
bspc config border_width         2         # width of border around window
bspc config focused_border_color "#82aaff" # color of border of focused window
bspc config window_gap           8         # gap between each window
bspc config top_padding         20         # for a status bar
bspc config focus_follows_pointer true     # change focus where mouse goes

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Configurations when hotplugging monitors
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true
